### ISSUE TITLE
Step 37 suddenly has a ton of errors

### ISSUE THREAD

**Issue by jbecker7** [yjerem/kilo-tutorial#56]
I was originally doing the tutorial in C++ and had no issues until step 37, so I switched to C to see if that was the problem. However, even in C I am getting the following errors:

## char *new = realloc(ab->b, ab->len + len);
```
expected unqualified-id [Parse Issue]Clang (c-cpp-flylint)
```

## if (new == NULL) return;
```
expected a type [Parse Issue]Clang (c-cpp-flylint)
```

##     memcpy(&new[ab->len], s, len);
```
expected a type [Parse Issue]Clang (c-cpp-flylint)
```

## ab->b = new;

```
expected a type [Parse Issue]Clang (c-cpp-flylint)
```

For reference, this is what I have, it should be identical to the source thus far but just formatted a little differently bc of my linter:

```
/*** append buffer ***/

struct abuf
{
    char *b;
    int len;
};

#define ABUF_INIT \
    {             \
        NULL, 0   \
    }

void abAppend(struct abuf *ab, const char *s, int len)
{
    char *new = realloc(ab->b, ab->len + len);
    if (new == NULL)
        return;
    memcpy(&new[ab->len], s, len);
    ab->b = new;
    ab->len += len;
}
void abFree(struct abuf *ab)
{
    free(ab->b);
}
```

I even tried to clone and run the completed source code, but the same errors popped up. I am new to C and C++, so I am assuming I am making some kind of goofy error, but I was having tons of fun, so I figured I might as well ask! Thanks :)

**Comment by raddari** [comment]
Hello, welcome to C :)
In C++ `new` is a keyword, so you cannot use it as an identifier; for example here:
```c++
char *new = realloc(ab->b, ab->len + len);
      ^^^
```
This seems to be the case for all of your error messages, which mention `new`.

Additionally C++ disallows implicit conversions from `void*`, which is returned by `realloc` (see why [here](https://stackoverflow.com/questions/23145730/why-does-c-forbid-implicit-conversion-of-void)). For the code snippet above to work, you'll have to cast the result of `realloc` to a `char*`.

There's a few "gotchas" where C code is not compatible with a C++ compiler, which might make it difficult to follow the tutorial in C++ if you are new. Looks like you've stumbled across two such cases here ;)

The code should compile fine as C however. The `c-cpp-flylint` extension could be reporting false positives if your project is still configured for C++ after you switched to a C compiler. Double check that these errors are also emitted from the C compiler itself, rather than just being a diagnostic from your extension.

**Comment by jbecker7** [comment]
@raddari You could've been super mean and dunked on me for this noobish question but instead you wrote a nice, thorough response that taught me something and helped me fix my problem. I really appreciate it and hope that you have a great day, and I think your dotfile repo is neat. Thanks :)

**Comment by raddari** [comment]
No worries, glad you figured out how to fix it! I hope you continue to enjoy programming :)
